version: "3.8"

networks:
  mynet:
    driver: bridge

volumes:
  consul_data:

services:

  # echo "YOUR_ACL_TOKEN" | docker secret create consul_token -
  consul:
    image: docker.repoifb.local/hashicorp/consul:latest
    container_name: consul
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -datacenter=dc1 -node=server1 -bind=0.0.0.0 -config-dir=/consul/config
    ports:
      - "8500:8500"
    volumes:
      - ./consul/config:/consul/config
      - consul_data:/consul/data
    environment:
      CONSUL_ACL_TOKEN: "ca01e2c4-f6c1-d582-6ba3-fc5f63208ded" # Replace with your actual token
      CONSUL_LOCAL_CONFIG: '{"acl": {"default_policy": "deny", "enable_token_persistence": true, "tokens": {"master": "ca01e2c4-f6c1-d582-6ba3-fc5f63208ded"}}}'
    networks:
      - mynet

  # registrator:
  #   image: docker.repoifb.local/pjhampton/registrator:latest
  #   container_name: registrator
  #   command: -internal -auth=ef86beb3-2e43-469f-6637-1762bf7e269f consul://consul:8500
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock
  #   depends_on:
  #     - consul
  #   networks:
  #     - mynet

  conship:
    build: ./conship
    container_name: conship
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
      - CONSUL_HTTP_TOKEN=ca01e2c4-f6c1-d582-6ba3-fc5f63208ded
    networks:
      - mynet
    depends_on:
      - consul


  nginx:
    image: docker.repoifb.local/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./shared-nginx-templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - consul
      # - conship
      #- registrator
    networks:
      - mynet

  myapp:
    image: docker.repoifb.local/crccheck/hello-world
    container_name: myapp
    networks:
      - mynet
    expose:
      - "8000"
    environment:
      - SERVICE_TAGS=virtual_host=myapp.local
    labels:
      - SERVICE_NAME=myapp
      - SERVICE_PORTS=8000
  
  myapp2:
    image: docker.repoifb.local/crccheck/hello-world
    container_name: myapp2
    networks:
      - mynet
    expose:
      - "8000"
    environment:
      - SERVICE_TAGS=virtual_host=myapp.local
    labels:
      - SERVICE_NAME=myapp
      - SERVICE_PORTS=8000

  consul-template:
    image: docker.repoifb.local/hashicorp/consul-template:latest
    container_name: consul-template
    command: -config=/etc/consul-template/config.hcl
    volumes:
      - ./nginx/templates/upstream.ctmpl:/etc/consul-template/upstream.ctmpl:ro
      - ./consul-template/config.hcl:/etc/consul-template/config.hcl:ro
      - ./shared-nginx-templates:/etc/nginx/templates
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - nginx
      - consul
      # - myapp
    networks:
      - mynet
