version: "3.8"

networks:
  mynet:
    driver: bridge

services:

  consul:
    image: docker.repoifb.local/hashicorp/consul:latest
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - mynet

  registrator:
    image: docker.repoifb.local/gliderlabs/registrator:latest
    container_name: registrator
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul
    networks:
      - mynet

  nginx:
    image: docker.repoifb.local/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./shared-nginx-templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - consul
      - registrator
    networks:
      - mynet

  # myapp:
  #   image: docker.repoifb.local/crccheck/hello-world
  #   container_name: myapp
  #   networks:
  #     - mynet
  #   expose:
  #     - "8000"
  #   environment:
  #     - SERVICE_TAGS=virtual_host=myapp.local
  #   labels:
  #     - "SERVICE_NAME=myapp"

  consul-template:
    image: docker.repoifb.local/hashicorp/consul-template:latest
    container_name: consul-template
    command: >
      -consul-addr=consul:8500
      -template="/etc/consul-template/upstream.ctmpl:/etc/nginx/templates/upstream.conf"
    volumes:
      - ./nginx/templates/upstream.ctmpl:/etc/consul-template/upstream.ctmpl:ro
      - ./shared-nginx-templates:/etc/nginx/templates
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - nginx
      - consul
      # - myapp
    networks:
      - mynet
