version: "3.8"

networks:
  mynet:
    driver: bridge

services:

  consul:
    image: consul:latest
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
    networks:
      - mynet

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates/upstream.ctmpl:/etc/nginx/templates/upstream.ctmpl:ro
    ports:
      - "80:80"
    depends_on:
      - consul
      - registrator
    networks:
      - mynet

  myapp:
    image: yourappimage:latest
    container_name: myapp
    networks:
      - mynet
    # بدون expose پورت به بیرون
    # فرض می‌کنیم سرویس روی 8080 در کانتینر اجرا می‌شود
