
  upstream consul {
    server 192.168.16.3:8300;
  }
  upstream myapp {
    server 192.168.16.5:8000;
  }
server {
  listen 80;
  server_name myapp.local;

  location / {
    proxy_pass http://myapp;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
